/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#eae6f4',
        'inverse-on-surface': '#f3effc',
        'on-error-container': '#93000a',
        background: '#fcf8ff',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#454386',
        'on-primary': '#ffffff',
        'inverse-primary': '#c3c0ff',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#c3c0ff',
        'secondary-fixed': '#e2dfff',
        'on-error': '#ffffff',
        'on-primary-fixed': '#0f0069',
        'error-container': '#ffdad6',
        'tertiary-container': '#a44100',
        'primary-container': '#4f46e5',
        'surface-container': '#f0ecf9',
        outline: '#777587',
        'secondary-container': '#b6b4ff',
        'on-background': '#1b1b24',
        'tertiary-fixed': '#ffdbcc',
        'on-surface': '#1b1b24',
        'surface-tint': '#4d44e3',
        'outline-variant': '#c7c4d8',
        'on-secondary-fixed-variant': '#413f82',
        'on-tertiary-fixed-variant': '#7b2f00',
        'on-primary-fixed-variant': '#3323cc',
        tertiary: '#7e3000',
        error: '#ba1a1a',
        'on-secondary-fixed': '#140f54',
        'primary-fixed': '#e2dfff',
        'surface-container-highest': '#e4e1ee',
        'on-secondary': '#ffffff',
        'surface-dim': '#dcd8e5',
        'on-primary-container': '#dad7ff',
        'surface-container-low': '#f5f2ff',
        'tertiary-fixed-dim': '#ffb695',
        primary: '#3525cd',
        'surface-variant': '#e4e1ee',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-container': '#ffd2be',
        'on-surface-variant': '#464555',
        'inverse-surface': '#302f39',
        surface: '#fcf8ff',
        secondary: '#58579b',
        'secondary-fixed-dim': '#c3c0ff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
};
